### ISSUE TITLE
undefined or null value leads to crash

### ISSUE THREAD

**Issue by fallingsappy** [Bonobolabs/time-picker#4]
If you provide null or undefined to value prop, it will lead to crash:

https://codesandbox.io/s/bonobolabs-time-picker-undefined-bug-nvcm7s

This behaviour is not present for rc-time-picker. I expect that input will be empty if undefined or null value provided.

**Comment by alexlouden** [comment]
Thanks! Fixed in d69457176494ffe4837064daa44dc9a322ba6c52, released in v0.1.1
